eureka.client.service-url.defaultZone=http://localhost:8765/eureka
eureka.instance.prefer-ip-address=true
logging.level.root=INFO
management.endpoints.web.exposure.include=health,info,metrics

# Zipkin server URL
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Sampling probability (1.0 = trace all requests)
management.tracing.sampling.probability=1.0

# Enable actuator endpoints
management.endpoints.web.exposure.include=*
